"""Universa: structure-switching architecture research scaffold."""

from universa.budgets import (
    BudgetCurve,
    BudgetInstance,
    ProbeInstance,
    Probes,
    budget_curve,
    identifiability_threshold,
    identification_residual,
    make_budget_instance,
    probe_instance,
    probe_operator,
)
from universa.category_instances import (
    GroupSwitchInstance,
    cyclic_group,
    group_as_category,
    induced_nerve_map,
    make_group_switch_instance,
    symmetric_group_3,
)
from universa.complexes2 import (
    induced_quotient_map,
    make_two_complex_switch_instance,
    two_complex,
)
from universa.discovery import (
    AdmissionDecision,
    DiscoveredConstraint,
    DiscoveryInsufficient,
    DiscoveryQuality,
    DiscoveryResult,
    DiscoveryRun,
    admit_to_library,
    discover_constraint,
    discovery_quality,
    run_discovery,
    synthesize_observations,
)
from universa.generators import (
    SwitchInstance,
    incidence_matrix,
    make_switch_instance,
    quotient_chain_map,
    random_connected_graph,
    subseed,
)
from universa.multihop import (
    DECOY_TOL,
    HopChain,
    compose,
    localize_misfit,
    make_multihop_instance,
)
from universa.nerve import FiniteCategory, nerve_chain_complex
from universa.operators import (
    SubspaceCertificate,
    misfit,
    nullspace_basis,
    projector,
    transport_and_project,
)
from universa.partial import (
    DEFAULT_FRACTIONS,
    ObservationModel,
    ObservedComplex,
    RankingRow,
    breakdown_fraction,
    observed_misfit,
    ranking_study,
)
from universa.sheaves import (
    Sheaf,
    SheafMorphism,
    coboundary,
    make_sheaf_switch_instance,
    planted_morphism,
    random_sheaf,
    to_chain_complex,
)
from universa.structures import ChainComplex, ChainMap

__all__ = [
    "AdmissionDecision",
    "BudgetCurve",
    "BudgetInstance",
    "ChainComplex",
    "ChainMap",
    "DECOY_TOL",
    "DEFAULT_FRACTIONS",
    "DiscoveredConstraint",
    "DiscoveryInsufficient",
    "DiscoveryQuality",
    "DiscoveryResult",
    "DiscoveryRun",
    "FiniteCategory",
    "GroupSwitchInstance",
    "HopChain",
    "ObservationModel",
    "ObservedComplex",
    "ProbeInstance",
    "Probes",
    "RankingRow",
    "Sheaf",
    "SheafMorphism",
    "SubspaceCertificate",
    "SwitchInstance",
    "admit_to_library",
    "breakdown_fraction",
    "budget_curve",
    "coboundary",
    "compose",
    "cyclic_group",
    "discover_constraint",
    "discovery_quality",
    "group_as_category",
    "identifiability_threshold",
    "identification_residual",
    "incidence_matrix",
    "induced_nerve_map",
    "induced_quotient_map",
    "localize_misfit",
    "make_budget_instance",
    "make_group_switch_instance",
    "make_multihop_instance",
    "make_sheaf_switch_instance",
    "make_switch_instance",
    "make_two_complex_switch_instance",
    "misfit",
    "nerve_chain_complex",
    "nullspace_basis",
    "observed_misfit",
    "planted_morphism",
    "probe_instance",
    "probe_operator",
    "projector",
    "quotient_chain_map",
    "random_connected_graph",
    "random_sheaf",
    "ranking_study",
    "run_discovery",
    "subseed",
    "symmetric_group_3",
    "synthesize_observations",
    "to_chain_complex",
    "transport_and_project",
    "two_complex",
]
